/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import Control.projectsController;
import Control.tasksController;
import Model.Projects;
import Model.Tasks;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        //                    TESTANDO CONTROLADOR DE PROJETOS
        /*projectsController projectController = new projectsController();
        Projects project = new Projects();
        Projects projectDois = new Projects();
        Projects project3 = new Projects();*/
        
        //project.setName("Projeto um");
        //project.setDescription("jhasdljkwqh");
        //projectController.save(project);
        
        //project.setName("Projeto 01");
        //project.setDescription("update test controller");
        //project.setId(1);
        //projectController.update(project);
        
        /*projectDois.setName("Projeto dois");
        projectDois.setDescription("ashdiouwq");
        projectController.save(projectDois);
        project3.setName("Projeto tres");
        project3.setDescription("ashoiduhasuid");
        projectController.save(project3);
        projectController.removeById(2);*/
        
        
        //List<Projects> projectList = projectController.getAll();
        //System.out.println("Total de projetos = " + projectList.size());
        
        //                 TESTANDO CONTROLADORES DE TAREFA
        
        /*tasksController taskController = new tasksController();
        Tasks task = new Tasks();
        Tasks task2 = new Tasks();
        Tasks task3 = new Tasks();
        Tasks task4 = new Tasks();*/
        
        //save
        /*task.setIdProject(1);
        task.setName("Tarefa um");
        task.setDescription("asudihaosidu");
        task.setIsCompleted(false);
        task.setNotes("asuihdoi");
        task.setDeadline(new Date());
        taskController.save(task);
        
        task2.setIdProject(1);
        task2.setName("Tarefa dois");
        task2.setDescription("asudidu");
        task2.setIsCompleted(false);
        task2.setNotes("asuihdasdzzoi");
        task2.setDeadline(new Date());
        taskController.save(task2);
        
        task3.setIdProject(3);
        task3.setName("Tarefa tres");
        task3.setDescription("zzzzzzzz");
        task3.setIsCompleted(false);
        task3.setNotes("zzzzzzi");
        task3.setDeadline(new Date());
        taskController.save(task3);*/
        
        //update
        /*task2.setIdProject(1);
        task2.setName("Tarefa dois");
        task2.setDescription("test update");
        task2.setIsCompleted(true);
        task2.setNotes("test update");
        task2.setDeadline(new Date());
        task2.setId(2);
        taskController.update(task2);*/
        
        //remove
        /*task4.setIdProject(3);
        task4.setName("Tarefa quatro");
        task4.setDescription("zxxxx");
        task4.setIsCompleted(false);
        task4.setNotes("zxxxxxi");
        task4.setDeadline(new Date());
        taskController.save(task4);*/
        //taskController.removeById(4);
        
        /*List<Tasks> taskList = taskController.getAll(1);
        System.out.println("Total de tarefas com idProject 1 = " + taskList.size());
        List<Tasks> taskList2 = taskController.getAll(3);
        System.out.println("Total de tarefas com idProject 3 = " + taskList2.size());*/
        
    }
}
